// src/components/Header/Header.tsx
import React, { useEffect, useCallback, useState } from "react";
import Logo from "./Logo.svg";
import styled, {css} from "styled-components";

interface IHeaderProps {
    collapsed: boolean
}

const Wrapper = styled.div<IHeaderProps>`
    display: flex;
    align-items: center;
    justify-content: ${props => props.collapsed ? "flex-start" : "center"};
    background: ${props => props.theme.backgroundHighlight};
    border-bottom: 3px ${props => props.theme.headerColor} solid;
    padding-top: ${props => props.collapsed ? "20px" : "50px"};
    padding-bottom: ${props => props.collapsed ? "20px" : "50px"};
    box-shadow: 0 3px 6px rgb(0, 0, 0, 0.16);
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 1;
`;

const LogoWrapper = styled.div<IHeaderProps>`
    transition: 0.5s;
    vertical-align: middle;
    width: ${props => props.collapsed ? "43px" : "135px"};
    height: ${props => props.collapsed ? "43px" : "135px"};
    ${props => props.collapsed && css`
        margin-left: 20px;
    `}
`;

const LogoText = styled.h1<IHeaderProps>`
    span.highlight {
        color: ${props => props.theme.headerColor};
    }
    font-size: ${props => props.collapsed ? "30px" : "100px"};
    color: ${props => props.theme.textColour};
    margin: 0 0 0 25px;
    text-shadow: 0 3px 6px rgb(0, 0, 0, 0.16);
    transition: 0.5s;
    ${props => props.collapsed && css`
        margin-left: 10px;
    `}
`;

export const Header: React.FC = () => {
    const [collapsed, setCollapsed] = useState(false);

    const listener = useCallback(() => {
        const thresh = 100;
        setCollapsed(
            document.documentElement.scrollTop > thresh ||
                document.body.scrollTop > thresh
        );
    }, []);

    useEffect(() => {
        window.addEventListener("scroll", listener);
        return () => window.removeEventListener("scroll", listener);
    }, [listener]);

    return (
        <Wrapper
            collapsed={collapsed}>
            <LogoWrapper
                collapsed={collapsed}
            >
                <img src={Logo} alt="Logo"/>
            </LogoWrapper>
            <LogoText
                collapsed={collapsed}
            >
                Rainm<span className={"highlight"}>.</span>io
            </LogoText>
        </Wrapper>
    );
};

// src/Header.svelte
<script lang="ts">
    import logo from './assets/Logo.svg'
    import { spring } from 'svelte/motion';

    const THRESHOLD = 200

    let y: number
    $: updateSprings(y)
    $: headerJustify = y < THRESHOLD ? "center" : "flex-start"

    let logoStyle = spring({
        size: 135,
        margin: 0,
    })

    let headerStyle = spring({
        padding: 50,
        fontSize: 100,
        margin: 25
    })

    const updateSprings = (scrollY: number) => {
        const yRatio = Math.min(scrollY / THRESHOLD, 1)
        logoStyle.set({
            size: 135 - 92 * yRatio,
            margin: 0 + 20 * yRatio
        })
        headerStyle.set({
            padding: 50 - 30 * yRatio,
            fontSize: 100 - 60 * yRatio,
            margin: 25 - 15 * yRatio
        })
    }
</script>

<svelte:window bind:scrollY={y}/>

<header style="--padding: {$headerStyle.padding}px; --justify-content: {headerJustify}">
    <img src={logo} alt="💧" id="logo" style="--size: {$logoStyle.size}px; --margin: {$logoStyle.margin}px"/>
    <h1 style="--font-size: {$headerStyle.fontSize}px; --margin: {$headerStyle.margin}px">
        Rainm<span class="highlight">.</span>io
    </h1>
</header>

<style lang="scss">
    @import "assets/scss/theme";

    header {
        display: flex;
        justify-content: var(--justify-content, "center");
        align-items: center;
        background: $backgroundHighlight;
        border-bottom: 3px $headerColor solid;
        box-shadow: $shadow;
        position: fixed;
        top: 0;
        width: 100%;
        z-index: 1;
        padding: var(--padding) 0;
    }

    img {
        vertical-align: middle;
        width: var(--size);
        height: var(--size);
        margin-left: var(--margin);
    }

    h1 {
        span.highlight {
            color: $headerColor;
        }
        color: $textColour;
        margin: 0;
        text-shadow: $shadow;
        font-size: var(--font-size);
        margin-left: var(--margin);
    }
</style>
